    # .streamlit/secrets.toml

    [credentials]
    # Store usernames as keys and their BCRYPT HASHED passwords as values
    "norfind" = "$2b$12$za/Rvn/G37cTujDHVgCLHeu0OvxujdVEX7b8bXqlxXV1W3c3ANQJC"